#############################################################################
# Makefile for building: exportToWindow
# Generated by qmake (3.1) (Qt 6.7.2)
# Project:  exportToWindow.pro
# Template: app
# Command: "C:\Program Files (x64)\Qt6\6.7.2\msvc2019_64\bin\qmake.exe" -o Makefile exportToWindow.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = "C:\Program Files (x64)\Qt6\6.7.2\msvc2019_64\bin\qmake.exe"
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = "C:\Program Files (x64)\Qt6\6.7.2\msvc2019_64\bin\qmake.exe" -install qinstall
QINSTALL_PROGRAM = "C:\Program Files (x64)\Qt6\6.7.2\msvc2019_64\bin\qmake.exe" -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = exportToWindow.res
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: exportToWindow.pro "..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf" "..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\spec_pre.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\common\windows-desktop.conf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\common\windows-vulkan.conf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\common\msvc-desktop.conf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\qconfig.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_graphs.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_graphs_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_grpc.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_grpc_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_grpcquick.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_grpcquick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_httpserver.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_httpserver_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_insighttracker.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_insighttracker_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_insighttrackerqml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_insighttrackerqml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_jsonrpc_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_languageserver_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdf.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdf_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdfquick.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdfquick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobuf.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobuf_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufqtcoretypes.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufqtcoretypes_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufqtguitypes.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufqtguitypes_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufwellknowntypes.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufwellknowntypes_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qdoccatch_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlbuiltins.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlbuiltins_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlls_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlnetwork.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2material.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimelineblendtrees.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimelineblendtrees_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboardsettings.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboardsettings_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webchannelquick.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webchannelquick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qt_functions.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qt_config.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\spec_post.prf" \
		.qmake.stash \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\exclusive_builds.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\common\msvc-version.conf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\toolchain.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\default_pre.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\win32\default_pre.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\resolve_config.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\default_post.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qmltypes.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\metatypes.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qml_debug.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\precompile_header.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\warn_on.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\permissions.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qt.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\resources_functions.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\resources.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\moc.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\win32\opengl.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\uic.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qmake_use.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\file_copies.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\win32\windows.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\testcase_targets.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\exceptions.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\yacc.prf" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\lex.prf" \
		exportToWindow.pro \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Quick.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6OpenGL.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Widgets.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Gui.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6QmlModels.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Qml.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Network.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Core.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6EntryPoint.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\build_pass.prf" \
		exportToWindow.qrc \
		shared\shared.qrc \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Quickd.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6OpenGLd.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Widgetsd.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Guid.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6QmlModelsd.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Qmld.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Networkd.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Cored.prl" \
		"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6EntryPointd.prl"
	$(QMAKE) -o Makefile exportToWindow.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\spec_pre.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\common\windows-desktop.conf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\common\windows-vulkan.conf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\common\msvc-desktop.conf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\qconfig.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_example_icons_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_graphs.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_graphs_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_grpc.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_grpc_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_grpcquick.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_grpcquick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_httpserver.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_httpserver_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_insighttracker.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_insighttracker_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_insighttrackerqml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_insighttrackerqml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_jsonrpc_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_languageserver_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdf.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdf_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdfquick.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdfquick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobuf.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobuf_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufqtcoretypes.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufqtcoretypes_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufqtguitypes.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufqtguitypes_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufwellknowntypes.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_protobufwellknowntypes_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qdoccatch_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlbuiltins.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlbuiltins_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlls_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlnetwork.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3deffects_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2material.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickeffects_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimelineblendtrees.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quicktimelineblendtrees_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_spatialaudio_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboardsettings.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboardsettings_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webchannelquick.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webchannelquick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qt_functions.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qt_config.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\spec_post.prf":
.qmake.stash:
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\exclusive_builds.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\common\msvc-version.conf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\toolchain.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\default_pre.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\win32\default_pre.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\resolve_config.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\default_post.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qmltypes.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\metatypes.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qml_debug.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\precompile_header.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\warn_on.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\permissions.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qt.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\resources_functions.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\resources.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\moc.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\win32\opengl.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\uic.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\qmake_use.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\file_copies.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\win32\windows.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\testcase_targets.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\exceptions.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\yacc.prf":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\lex.prf":
exportToWindow.pro:
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Quick.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6OpenGL.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Widgets.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Gui.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6QmlModels.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Qml.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Network.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Core.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6EntryPoint.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\mkspecs\features\build_pass.prf":
exportToWindow.qrc:
shared\shared.qrc:
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Quickd.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6OpenGLd.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Widgetsd.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Guid.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6QmlModelsd.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Qmld.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Networkd.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6Cored.prl":
"..\..\..\..\Program Files (x64)\Qt6\6.7.2\msvc2019_64\lib\Qt6EntryPointd.prl":
qmake: FORCE
	@$(QMAKE) -o Makefile exportToWindow.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) exportToWindow.vc.pdb
	-$(DEL_FILE) exportToWindow.ilk
	-$(DEL_FILE) exportToWindow.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash exportToWindow.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
